---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  labels:
    spawn-eigr.io.actor-system: game-system
  name: spawn-dice-game
  namespace: default
spec:
  host:
    embedded: true
    image: eigr/dice-game-example:0.5.3
    ports:
      - name: "http"
        containerPort: 8800
  autoscaler:
    max: 1
