---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-dice-game
  system: game-system
  namespace: default
spec:
  autoscaler: # Optional
    max: 6
  host:
    embedded: true
    image: eigr/dice-game-example:0.1.1
    ports:
      - name: "http"
        containerPort: 8800
